export {default as Home} from "./Home";
export {default as Events} from "./Events";
export {default as Info} from "./Info";
export {default as Pictures} from "./Pictures";
export {default as Projects} from "./Projects";
export {default as Ace} from "./Ace";
export {default as Contact} from "./Contact";
export {default as Conduct} from "./Conduct";
export {default as Courses} from "./Courses"
